version: '3'
services:
  dkron:
    image: dkron/dkron
    ports:
      - "18080:8080"
      - "8946"
      - "6868"
    command: agent --server --log-level=debug --bootstrap-expect=1
    volumes:
      - ./data/:/opt/local/dkron/dkron.data/