version: '2'
services:
  dkron:
    image: dkron/dkron:v2.0.4
    container_name: leader1
    ports:
      - "8080:8080"
      - "6868"
    command: agent
    volumes:
      - ./datas/leader1/:/opt/local/dkron/dkron.data/
      - ./config/foo.yml:/opt/local/dkron/config/dkron.yml
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  dkron-server:
    container_name: server1
    image: dkron/dkron:v2.0.4
    ports:
      - "8080"
      - "8946"
      - "6868"
    links:
      - dkron:dkron
    volumes:
      - ./datas/server1/:/opt/local/dkron/dkron.data/
      - ./config/foo2.yml:/opt/local/dkron/config/dkron.yml
    environment:
      - GODEBUG=netdns=go
    command: agent --bootstrap-expect=3 --retry-join=dkron --node-name=foo2
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
  dkron-agent:
    container_name: agent1
    image: dkron/dkron:v2.0.4
    ports:
      - "8946"
    links:
      - dkron:dkron
      - dkron-server:dkServer
    environment:
      - GODEBUG=netdns=go
    command: agent --retry-join=dkServer --node-name=foo3
    volumes:
      - ./config/foo3.yml:/opt/local/dkron/config/dkron.yml
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1