version: '2'
services:
  dkron:
    image: dkron/dkron:v2.0.4
    container_name: seed
    ports:
      - "8080:8080"
      - "6868"
    command: agent --server --bootstrap-expect=1 --log-level=debug --node-name=seed
    volumes:
      - ./datas/seed/:/opt/local/dkron/dkron.data/
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
  dkron-server:
    container_name: server1
    image: dkron/dkron:v2.0.4
    ports:
      - "8081:8080"
      - "8946"
      - "6868"
    links:
      - dkron:dkron
    volumes:
      - ./datas/server1/:/opt/local/dkron/dkron.data/
    environment:
      - GODEBUG=netdns=go
    command: agent --server --bootstrap-expect=3 --retry-join=dkron --node-name=server1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  dkron-server2:
    container_name: server2
    image: dkron/dkron:v2.0.4
    ports:
      - "8082:8080"
      - "8946"
      - "6868"
    links:
      - dkron:dkron
    volumes:
      - ./datas/server2/:/opt/local/dkron/dkron.data/
    environment:
      - GODEBUG=netdns=go
    command: agent --server --bootstrap-expect=3 --retry-join=dkron --node-name=server2
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  dkron-agent:
    container_name: agent1
    image: dkron/dkron:v2.0.4
    ports:
      - "8946"
    links:
      - dkron:dkron
    environment:
      - GODEBUG=netdns=go
    command: agent --retry-join=dkron --node-name=agent1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1